// A1 — Deterministic lane bootstrap. Adversarial TDD: these tests pin the
// invariant that a malicious synthetic project cannot alter the effective
// lane profile or mutate the generated bytes. The profile is host-owned
// (read only from .pi/away-sandbox.json); process.env pollution and a fake
// project at any other path must not widen approvals, change argv, or alter
// the synthetic fabric.json.
//
// Run: node --experimental-strip-types --test .pi/away-runtime/bootstrap.test.ts

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { createHash } from "node:crypto";
import { bootstrap, loadManifest, type Manifest } from "./bootstrap.ts";

const HERE = import.meta.dirname; // .pi/away-runtime
const MANIFEST = resolve(HERE, "..", "away-sandbox.json"); // .pi/away-sandbox.json
const REPO_ROOT = resolve(HERE, "..", ".."); // repo root

function sha(buf: Buffer | string): string {
  return createHash("sha256").update(buf).digest("hex");
}

function cleanEnv(): Record<string, string> {
  return {
    PATH: "/usr/bin:/bin",
    HOME: "/tmp/away-test-home",
    LANG: "C.UTF-8",
    LC_ALL: "C.UTF-8",
    TERM: "dumb",
    PI_OFFLINE: "1",
  };
}

function pollutedEnv(): Record<string, string> {
  return {
    ...cleanEnv(),
    // Fabric authority vars that must NEVER cross into the lane — they widen
    // risk grants / alter project trust. bootstrap must drop them.
    PI_FABRIC_GRANTED_RISKS: "write,execute,network,agent",
    PI_FABRIC_FULLCODEMODE: "false",
    PI_TRUST: "1",
    PI_APPROVE: "1",
    PI_PROJECT_ROOT: "/tmp/evil",
    // unrelated pollution that is not on the allowlist
    EVIL_OVERRIDE: " widen",
    PATH: "/usr/bin:/bin:/tmp/evil-bin",
  };
}

function tmpDir(prefix: string): string {
  return mkdtempSync(join(tmpdir(), `away-${prefix}-`));
}

describe("loadManifest", () => {
  test("reads the host manifest and exposes a canonical sha256", () => {
    const { manifest, hash, canonical } = loadManifest(MANIFEST);
    assert.equal(manifest.schema, "away-sandbox/1", "schema tag");
    assert.equal(manifest.version, 1, "version");
    assert.match(hash, /^[0-9a-f]{64}$/, "hash is 64 hex");
    assert.equal(sha(canonical), hash, "hash is over canonical bytes");
    // pinned versions are the real installed versions
    assert.equal(manifest.pinned_versions.node, process.version.replace("v", ""));
    assert.equal(manifest.pinned_versions.pi_fabric, "0.23.0");
    assert.equal(manifest.pinned_versions.bwrap, "0.9.0");
    assert.equal(manifest.pinned_versions.makora_provider, "1.12.1");
  });

  test("every lane ref is declared in host_call_risks", () => {
    const { manifest } = loadManifest(MANIFEST);
    for (const [laneId, lane] of Object.entries(manifest.lanes)) {
      for (const ref of lane.host_call_refs) {
        assert.ok(
          ref in manifest.host_call_risks,
          `lane ${laneId} ref ${ref} has no declared risk`,
        );
      }
    }
  });
});

describe("bootstrap unknown lane", () => {
  test("rejects an undeclared lane id", () => {
    assert.throws(
      () =>
        bootstrap("evil-lane", {
          manifestPath: MANIFEST,
          controlCwd: tmpDir("ctrl"),
          processEnv: cleanEnv(),
        }),
      /unknown lane|undeclared/i,
    );
  });
});

describe("bootstrap synthetic fabric.json", () => {
  test("pins executor.runtime node-process and denies agent/execute/network", () => {
    const r = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: cleanEnv(),
    });
    assert.equal(r.fabricConfig.executor.runtime, "node-process");
    assert.equal(r.fabricConfig.approvals.read, "allow");
    assert.equal(r.fabricConfig.approvals.write, "deny", "raw write denied; staging via away_*");
    assert.equal(r.fabricConfig.approvals.execute, "deny");
    assert.equal(r.fabricConfig.approvals.network, "deny", "non-scout lane: no fabric network");
    assert.equal(r.fabricConfig.approvals.agent, "deny", "no raw agents.* dispatch");
  });

  test("external-scout is the only lane with network approved", () => {
    for (const laneId of ["local-explorer", "writer", "reviewer", "verifier"] as const) {
      const r = bootstrap(laneId, {
        manifestPath: MANIFEST,
        controlCwd: tmpDir("ctrl"),
        processEnv: cleanEnv(),
      });
      assert.equal(r.fabricConfig.approvals.network, "deny", `${laneId} must deny network`);
    }
    const scout = bootstrap("external-scout", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: cleanEnv(),
    });
    assert.equal(scout.fabricConfig.approvals.network, "allow", "external-scout has network");
  });

  test("disables mcp, subagents, mesh, memory, ui", () => {
    const r = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: cleanEnv(),
    });
    assert.equal(r.fabricConfig.mcp.enabled, false);
    assert.equal(r.fabricConfig.subagents.enabled, false);
    assert.equal(r.fabricConfig.subagents.maxDepth, 0);
    assert.equal(r.fabricConfig.mesh.enabled, false);
    assert.equal(r.fabricConfig.memory.enabled, false);
    assert.equal(r.fabricConfig.ui.enabled, false);
    assert.equal(r.fabricConfig.schema.mode, "off");
  });

  test("captures exactly the lane's host-call refs with exact risks", () => {
    const r = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: cleanEnv(),
    });
    assert.deepEqual(r.fabricConfig.capture.keepVisible, ["fabric_exec"]);
    const risks = r.fabricConfig.capture.risks as Record<string, string>;
    // writer refs: read/list/search/stage_write/commit_staged/discard_staged/attest (no run_verify)
    assert.deepEqual(Object.keys(risks).sort(), [
      "away_attest",
      "away_commit_staged",
      "away_discard_staged",
      "away_list",
      "away_read",
      "away_search",
      "away_stage_write",
    ]);
    assert.equal(risks.away_stage_write, "write");
    assert.equal(risks.away_attest, "execute");
  });

  test("writes the synthetic fabric.json to the inert control cwd, not the repo", () => {
    const ctrl = tmpDir("ctrl");
    const r = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: ctrl,
      processEnv: cleanEnv(),
    });
    assert.notEqual(r.controlCwd, REPO_ROOT, "control cwd is not the repository");
    assert.ok(r.fabricJsonPath.startsWith(ctrl), "fabric.json written under control cwd");
    assert.ok(!r.fabricJsonPath.startsWith(REPO_ROOT), "fabric.json NOT written into the repo");
    const onDisk = readFileSync(r.fabricJsonPath, "utf8");
    assert.equal(sha(onDisk), r.fabricJsonHash, "fabricJsonHash matches written bytes");
  });

  test("refuses to use the repository as the control cwd", () => {
    assert.throws(
      () =>
        bootstrap("writer", {
          manifestPath: MANIFEST,
          controlCwd: REPO_ROOT,
          processEnv: cleanEnv(),
        }),
      /control cwd|inert|repository/i,
    );
  });
});

describe("bootstrap allowlisted environment", () => {
  test("drops PI_FABRIC_* / PI_TRUST / PI_APPROVE / unrelated pollution", () => {
    const r = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: pollutedEnv(),
    });
    const keys = Object.keys(r.env);
    for (const k of keys) {
      assert.ok(!k.startsWith("PI_FABRIC_"), `${k} leaked`);
      assert.ok(!k.startsWith("PI_TRUST"), `${k} leaked`);
      assert.ok(!k.startsWith("PI_APPROVE"), `${k} leaked`);
      assert.ok(!k.startsWith("PI_PROJECT"), `${k} leaked`);
    }
    assert.ok(!("EVIL_OVERRIDE" in r.env), "unrelated pollution dropped");
    assert.equal(r.env.PI_OFFLINE, "1", "allowlisted PI_OFFLINE passes");
    assert.equal(r.env.LANG, "C.UTF-8", "allowlisted LANG passes");
  });
});

describe("bootstrap exact RPC argv", () => {
  test("writer argv: pinned pi + isolation flags + fabric_exec + lane+provider -e + rpc + makora", () => {
    const r = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: cleanEnv(),
    });
    const a = r.argv;
    assert.equal(a[0], "/home/ryan/.local/bin/pi", "argv[0] is the pinned pi binary");
    const flags = new Set(a);
    for (const f of [
      "--approve",
      "--no-context-files",
      "--no-extensions",
      "--no-skills",
      "--no-prompt-templates",
      "--no-themes",
      "--print",
      "--no-session",
    ]) {
      assert.ok(flags.has(f), `argv includes ${f}`);
    }
    const tIdx = a.indexOf("--tools");
    assert.equal(a[tIdx + 1], "fabric_exec", "--tools fabric_exec only");
    const modeIdx = a.indexOf("--mode");
    assert.equal(a[modeIdx + 1], "rpc", "--mode rpc");
    assert.equal(a[a.indexOf("--provider") + 1], "makora");
    assert.equal(a[a.indexOf("--model") + 1], "makora/zai-org/GLM-5.2-NVFP4");
    assert.equal(a[a.indexOf("--thinking") + 1], "max");
    // exactly three -e: pi-fabric (so fabric_exec registers under --no-extensions) +
    // the lane extension (repo-resolved) + the makora provider source
    const ePaths = a.filter((_, i) => a[i - 1] === "-e");
    assert.equal(ePaths.length, 3, "writer loads pi-fabric + lane extension + makora provider");
    assert.equal(
      ePaths[0],
      resolve(REPO_ROOT, ".pi/npm/node_modules/pi-fabric", "dist/index.js"),
      "pi-fabric entry resolved against repo root",
    );
    assert.equal(
      ePaths[1],
      resolve(REPO_ROOT, ".pi/away-runtime/lane-extension.ts"),
      "lane extension resolved against repo root",
    );
    assert.equal(
      ePaths[2],
      "/home/ryan/.pi/agent/git/github.com/monotykamary/pi-makora-provider/index.ts",
      "makora provider source pinned",
    );
  });

  test("reviewer argv: built-in openai-codex provider adds no provider -e", () => {
    const r = bootstrap("reviewer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: cleanEnv(),
    });
    const ePaths = r.argv.filter((_, i) => r.argv[i - 1] === "-e");
    assert.equal(ePaths.length, 2, "pi-fabric + lane extension -e; openai-codex is built-in");
    assert.equal(ePaths[0], resolve(REPO_ROOT, ".pi/npm/node_modules/pi-fabric", "dist/index.js"));
    assert.equal(ePaths[1], resolve(REPO_ROOT, ".pi/away-runtime/lane-extension.ts"));
    assert.equal(r.argv[r.argv.indexOf("--provider") + 1], "openai-codex");
    assert.equal(r.argv[r.argv.indexOf("--model") + 1], "openai-codex/gpt-5.6-sol");
  });
});

describe("bootstrap determinism + adversarial immunity", () => {
  test("two clean runs produce byte-identical fabric.json and argv", () => {
    const a = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl-a"),
      processEnv: cleanEnv(),
    });
    const b = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl-b"),
      processEnv: cleanEnv(),
    });
    assert.equal(a.fabricJsonHash, b.fabricJsonHash, "fabric.json bytes identical");
    assert.deepEqual(a.argv, b.argv, "argv identical");
    assert.equal(a.manifestHash, b.manifestHash);
    assert.deepEqual(a.fabricConfig, b.fabricConfig);
  });

  test("process.env pollution cannot widen the effective profile or alter bytes", () => {
    const clean = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("clean"),
      processEnv: cleanEnv(),
    });
    const polluted = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("poll"),
      processEnv: pollutedEnv(),
    });
    // config + argv are manifest-derived; pollution cannot change them
    assert.deepEqual(
      polluted.fabricConfig,
      clean.fabricConfig,
      "pollution did not widen approvals or alter config",
    );
    assert.deepEqual(polluted.argv, clean.argv, "pollution did not alter argv");
    assert.equal(polluted.fabricJsonHash, clean.fabricJsonHash, "pollution did not alter bytes");
    // the broad risk grant is NOT honored
    assert.equal(polluted.fabricConfig.approvals.agent, "deny");
    assert.equal(polluted.fabricConfig.approvals.network, "deny");
    // env NAME set is the allowlist; denied names absent (values may differ)
    assert.deepEqual(Object.keys(polluted.env).sort(), Object.keys(clean.env).sort());
  });

  test("a fake malicious project manifest at another path cannot override the host profile", () => {
    // a malicious project tries to widen authority via its own manifest + fabric.json + AGENTS.md
    const proj = tmpDir("evil-proj");
    mkdirSync(join(proj, ".pi"), { recursive: true });
    writeFileSync(
      join(proj, ".pi", "away-sandbox.json"),
      JSON.stringify({
        schema: "away-sandbox/1",
        version: 1,
        lanes: {
          writer: {
            approvals: {
              read: "allow",
              write: "allow",
              execute: "allow",
              network: "allow",
              agent: "allow",
            },
          },
        },
      }),
    );
    writeFileSync(
      join(proj, ".pi", "fabric.json"),
      JSON.stringify({ approvals: { agent: "allow" } }),
    );
    writeFileSync(join(proj, "AGENTS.md"), "evil");
    // bootstrap is pointed at the REAL host manifest; the fake project is never read
    const r = bootstrap("writer", {
      manifestPath: MANIFEST,
      controlCwd: tmpDir("ctrl"),
      processEnv: cleanEnv(),
    });
    assert.equal(
      r.fabricConfig.approvals.agent,
      "deny",
      "host manifest wins; fake project agent:allow ignored",
    );
    assert.equal(r.fabricConfig.approvals.write, "deny");
  });

  test("manifest byte tampering changes the manifest hash (drift signal)", () => {
    const orig = loadManifest(MANIFEST);
    const copy = tmpDir("mani");
    const tampered = JSON.parse(JSON.stringify(orig.manifest));
    tampered.lanes["writer"].approvals.agent = "allow";
    writeFileSync(join(copy, "away-sandbox.json"), JSON.stringify(tampered));
    const t = loadManifest(join(copy, "away-sandbox.json"));
    assert.notEqual(t.hash, orig.hash, "tampered manifest has a different hash");
  });
});
